<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Antecipacao.Application.csproj" />
    <ProjectReference Include="..\Domain\Antecipacao.Domain.csproj" />
  </ItemGroup>

</Project>
